In [3]:
import numpy as np
ratings = np.array([[3, 3, 4, 0, 4, 2, 3, 0],
                    [3, 5, 4, 3, 3, 0, 0, 4],
                    [0, 4, 0, 5, 0, 0, 2, 1],
                    [2, 0, 0, 4, 0, 4, 4, 5]])
Ub = (ratings>0).astype(int)
print(Ub)

def jaccard(a,b):
    return (a*b).sum()/((a+b)>0).sum()

users = ["firechicken","mike0702","zephyros","dadvador"]

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = jaccard(Ub[i],Ub[j])
        if i<j:
            print(users[i]+'-'+users[j], jaccard(Ub[i],Ub[j]))

print(simmat)

[[1 1 1 0 1 1 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 1 1]
 [1 0 0 1 0 1 1 1]]
firechicken-mike0702 0.5
firechicken-zephyros 0.25
firechicken-dadvador 0.375
mike0702-zephyros 0.42857142857142855
mike0702-dadvador 0.375
zephyros-dadvador 0.5
[[1.         0.5        0.25       0.375     ]
 [0.5        1.         0.42857143 0.375     ]
 [0.25       0.42857143 1.         0.5       ]
 [0.375      0.375      0.5        1.        ]]


In [4]:
def cos(a,b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = cos(Ub[i],Ub[j])
        if i<j:
            print(users[i]+'-'+users[j], cos(Ub[i],Ub[j]))
print(simmat)   

firechicken-mike0702 0.6666666666666667
firechicken-zephyros 0.4082482904638631
firechicken-dadvador 0.5477225575051661
mike0702-zephyros 0.6123724356957946
mike0702-dadvador 0.5477225575051661
zephyros-dadvador 0.6708203932499369
[[1.         0.66666667 0.40824829 0.54772256]
 [0.66666667 1.         0.61237244 0.54772256]
 [0.40824829 0.61237244 1.         0.67082039]
 [0.54772256 0.54772256 0.67082039 1.        ]]


In [5]:
Ur = (ratings>=3).astype(int)
print(Ur)

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = jaccard(Ur[i],Ur[j])
        if i<j:
            print(users[i]+'-'+users[j], jaccard(Ur[i],Ur[j]))

[[1 1 1 0 1 0 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 1 1]]
firechicken-mike0702 0.5714285714285714
firechicken-zephyros 0.16666666666666666
firechicken-dadvador 0.125
mike0702-zephyros 0.3333333333333333
mike0702-dadvador 0.25
zephyros-dadvador 0.2
